### PR TITLE
Fix .sm chart conversion

### PR DESCRIPTION
**Pull request by Discookie**
Fixes (some of) #29.

Tested with the maps in #29, they all synced well. A test map for all measure types was also added.

### CODE REVIEW

**Comment by YaLTeR** [comment]
Please add tests for the things you fixed. See osu conversion tests as an example.

**Comment by Discookie** [comment]
Added a constructed test case; and well, apparently there are many deeper issues with the parser than it first seemed. There's missing HitObjects, way too many TimingPoints, and their accuracy is all over the place.

**Comment by Swan** [comment]
This is a good start and seems to fix where there are slight bpm differences, but it still seems go off-sync with major bpm changes.

[Example File](https://drive.google.com/file/d/1zKXvz5_YhBqxusYE_pCqexbYvXrHnuv-/view?usp=sharing)

**Comment by Discookie** [comment]
Today I learned that BPM changes can exist inside a measure, it's fixed now.

Regarding the example you linked:
There's both a .sm and a .ssc file in there, and Stepmania prefers the .ssc file.  
And in .ssc, there's separate local BPMs for all maps - where it halves the BPM at beat 89. But in the global BPM values, this halving is not there.

Because .sm doesn't support per-map BPM changes, only the global BPMs are saved into it - thus the desync.  
You can verify this yourself by just not copying the .ssc file, and see that it's also desynced.

**Comment by Discookie** [comment]
Here's a map to test the accuracy of converting:  
[File from Yolo Dumps 1](https://1drv.ms/u/s!An-sVdmy2fkGiut7TuKSzScXuTDIsg?e=MEt4GX)

This map is converted well enough already, but if it was accurate enough, it would have sections that are all the same color.

**Pull request closed without merging**
