### PR TITLE
Fix precision error and last measure of .sm files

### PR DESCRIPTION
**Pull request by Kizuna-dev**
As of currently, offset are considered as float in the parser, which is actually false, they are double. Because of that, plenty of chart when parsed start to have their note shifting from the timing line, creating plenty of white note.

Example : 
https://cdn.discordapp.com/attachments/733326021302026332/817556131185950790/2021-03-06_01-34-06.mp4
https://cdn.discordapp.com/attachments/733326021302026332/817558843260928020/2021-03-06_01-43-50.mp4

In the beginning, i preview the chart in the current version, using float. We can notice that after a moment, all note shift to white, because they are misplaced in time because of that precision error. 
Tho, in the second part of the video, in the build using the fix, you can notice that all note are snaped correctly with their intended color.

---------------------------------------------------------------------------------

Second, the measure. The ";" at the very end of the file was not taken into account, because of that, in the last measure, the ";" is actually considered a note, so for example, instead of having a measure of 16, it end up being 17, which create this kind of wrong snap : 
unknown

(ArrowVortex on the right for comparaison)

---------------------------------------------------------------------------------

Also yes, i am aware that updating this will probably break every existing leaderboard for all stepmania files, but at least they all will be converted as accurately as possible, and also fix all the broken chart.

### CODE REVIEW

**Review by Kizuna-dev — COMMENTED** [review]
I forgot this, it broke chart with multiple bpm, now it work correctly on all chart

**Review by Kizuna-dev — COMMENTED** [review]
add more precision to beat, because float is not enough apparently (tested on some chart)

**Review by Kizuna-dev — COMMENTED** [review]
Last update (i hope), now every chart that i found and received as test sample work perfectly and everything is placed exactly on their timing.

**Review by Kizuna-dev — COMMENTED** [review]
To be fair i haven't tested anything related to STOP, this is just to make it similar to the previous condition

**Review by Swan — CHANGES_REQUESTED** [review]
This is a bit better, but the shift still occurs towards the end on this one. Some notes are green, others are white. [example.zip](https://github.com/Quaver/Quaver.API/files/6137039/example.zip)

**Comment by Kizuna-dev** [comment]
Because of my mistake of using the master branch for this PR it looks kinda bad with all the update, and also with my commit naming being not accurate to what i changed, i'm gonna close this PR and make a new and more cleaner one, with proper naming, and also not use the master branch this time.

**Pull request closed without merging**
